version: '3'
services: 
  mongo: 
    image: 'mongo'
    restart: always
    ports:
      - "27017:27017"

  redis: 
    image: 'redis:latest'
    restart: always
    ports: 
      - "6379:6379"
  
  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app

  aws_service:
    depends_on:
      - mongo
      - redis
    build:
      dockerfile: Dockerfile
      context: ./aws_service
    volumes: 
      - /aws_app/node_modules
      - ./aws_service:/aws_app
    environment: 
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=37017
      - MONGODB_USER=root
      - MONGODB_PASS=password123
    links:
      - mongo
      - redis
    ports:
      - "5000:5000"
  webapp:
    depends_on:
      - mongo
      - redis
    build:
      dockerfile: Dockerfile
      context: ./webapp
    volumes: 
      - /aws_app/node_modules
      - ./aws_service:/aws_app
    environment: 
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=37017
      - MONGODB_USER=root
      - MONGODB_PASS=password123
    links:
      - mongo
      - redis
    ports:
      - "6426:6426"

  aws_testrunner:
    depends_on:
      - mongo
      - redis
    build:
      dockerfile: Dockerfile
      context: ./aws_service
    volumes: 
      - /aws_app/node_modules
      - ./aws_service:/aws_app
    environment: 
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=37017
      - MONGODB_USER=root
      - MONGODB_PASS=password123
    links:
      - mongo
      - redis
    ports:
      - "6000:6000"

  nginx: 
    depends_on:
      - aws_service
      - client
      - aws_testrunner
      - webapp
    restart: always
    build: 
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "8080:80"